apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: asia-southeast1-docker.pkg.dev/ticketing-447009/ticketing-docker-hub/client:latest
          resources:
            requests:
              memory: "500M"
              cpu: "200m"
            limits:
              memory: "1G"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
