name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
env:
  GAR_LOCATION: asia-southeast1 # TODO: update region of the Artifact Registry

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Set up Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v1
      #   with:
      #     project_id: ${{ secrets.GCP_PROJECT }}
      #     service_account_key: ${{ secrets.GCP_SA_KEY }}
      
      - id: 'auth'
        name: Set up Cloud SDK
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Docker configuration
        run: |-
        echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev

      - name: Build Docker images
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/auth:latest ./auth
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/client:latest ./client
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/expiration:latest ./expiration
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/orders:latest ./orders
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/payments:latest ./payments
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/tickets:latest ./tickets

      - name: Push Docker images to Google Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/auth:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/client:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/expiration:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/orders:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/payments:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/tickets:latest

      - name: Configure kubectl
        run: |
          echo ${{ secrets.GCP_SA_KEY }} > ${HOME}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud --quiet config set project ${{ secrets.GCP_PROJECT }}
          gcloud --quiet config set compute/region ${{ secrets.GCP_REGION }}
          gcloud --quiet container clusters get-credentials ${{ secrets.GKE_CLUSTER }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f infra/k8s/auth-depl.yaml
          kubectl apply -f infra/k8s/auth-mongo-depl.yaml
          kubectl apply -f infra/k8s/client-depl.yaml
          kubectl apply -f infra/k8s/expiration-depl.yaml
          kubectl apply -f infra/k8s/expiration-redis-depl.yaml
          kubectl apply -f infra/k8s/ingress-srv.yaml
          kubectl apply -f infra/k8s/nats-depl.yaml
          kubectl apply -f infra/k8s/orders-depl.yaml
          kubectl apply -f infra/k8s/orders-mongo-depl.yaml
          kubectl apply -f infra/k8s/payments-depl.yaml
          kubectl apply -f infra/k8s/payments-mongo-depl.yaml
          kubectl apply -f infra/k8s/tickets-depl.yaml
          kubectl apply -f infra/k8s/tickets-mongo-depl.yaml
          kubectl set image deployment/auth auth=gcr.io/${{ secrets.GCP_PROJECT }}/auth:latest
          kubectl set image deployment/client client=gcr.io/${{ secrets.GCP_PROJECT }}/client:latest
          kubectl set image deployment/expiration expiration=gcr.io/${{ secrets.GCP_PROJECT }}/expiration:latest
          kubectl set image deployment/orders orders=gcr.io/${{ secrets.GCP_PROJECT }}/orders:latest
          kubectl set image deployment/payments payments=gcr.io/${{ secrets.GCP_PROJECT }}/payments:latest
          kubectl set image deployment/tickets tickets=gcr.io/${{ secrets.GCP_PROJECT }}/tickets:latest
